//! Multi-Agent Orchestration coordinator in Rust.

use crate::evaluator::{EvaluationVerdict, ResultEvaluator};
use mag_agent::AgentDefinition;
use mag_common::{AgentRole, TaskRequest, TaskResult};
use mag_config::ProjectConfig;
use mag_git::GitManager;
use mag_scheduler::TaskScheduler;
use mag_storage::Storage;
use mag_task::Task;
use mag_worker::execute_task_for_agent;
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use thiserror::Error;

#[derive(Error, Debug)]
pub enum OrchestratorError {
    #[error("Storage error: {0}")]
    Storage(#[from] mag_storage::StorageError),
    #[error("Git error: {0}")]
    Git(#[from] mag_git::GitError),
    #[error("Task execution failed permanently: {0}")]
    Fatal(String),
}

pub struct Orchestrator {
    pub config: ProjectConfig,
    pub storage: Storage,
    pub git: GitManager,
    pub evaluator: ResultEvaluator,
    pub repo_path: PathBuf,
}

impl Orchestrator {
    pub fn new<P: AsRef<Path>>(repo_path: P, db_path: P) -> Result<Self, OrchestratorError> {
        let repo_buf = repo_path.as_ref().to_path_buf();
        let storage = Storage::new(db_path)?;
        let git = GitManager::new(&repo_buf);
        let config = ProjectConfig::default_project("mag-project");
        let evaluator = ResultEvaluator::new(config.manager.max_retries);

        Ok(Self {
            config,
            storage,
            git,
            evaluator,
            repo_path: repo_buf,
        })
    }

    pub fn extract_target_directory(&self, prompt: &str) -> PathBuf {
        for word in prompt.split_whitespace() {
            let trimmed = word.trim_matches(|c| c == '\'' || c == '"' || c == '`' || c == 'に' || c == 'へ');
            if trimmed.starts_with('/') || trimmed.starts_with("./") {
                return PathBuf::from(trimmed);
            }
        }
        self.repo_path.clone()
    }

    pub fn decompose_requirement(&self, prompt: &str) -> Result<Vec<Task>, OrchestratorError> {
        let existing = self.storage.list_tasks()?;
        let base_num = existing.len() + 1;

        let id1 = format!("TASK-{:03}", base_num);
        let id2 = format!("TASK-{:03}", base_num + 1);
        let id3 = format!("TASK-{:03}", base_num + 2);
        let id4 = format!("TASK-{:03}", base_num + 3);
        let id5 = format!("TASK-{:03}", base_num + 4);

        let t1 = Task::new(&id1, format!("Spec: {}", prompt), format!("Architecture notes for: {}", prompt), "agent-e", AgentRole::Researcher);
        let t2 = Task::new(&id2, format!("Implementation: {}", prompt), format!("Implement source for: {}", prompt), "agent-a", AgentRole::Developer)
            .with_dependencies(vec![id1]);
        let t3 = Task::new(&id3, format!("Testing: {}", prompt), format!("Run tests for: {}", prompt), "agent-b", AgentRole::Tester)
            .with_dependencies(vec![id2]);
        let t4 = Task::new(&id4, format!("Review: {}", prompt), format!("Review code for: {}", prompt), "agent-c", AgentRole::Reviewer)
            .with_dependencies(vec![id3]);
        let t5 = Task::new(&id5, format!("Security: {}", prompt), format!("Security audit for: {}", prompt), "agent-d", AgentRole::Security)
            .with_dependencies(vec![id4]);

        let tasks = vec![t1, t2, t3, t4, t5];
        for t in &tasks {
            self.storage.save_task(t)?;
        }

        Ok(tasks)
    }

    pub fn execute_task_locally(&self, task: &mut Task, target_dir: Option<&Path>) -> Result<TaskResult, OrchestratorError> {
        let agent = AgentDefinition::default_for_role(task.role);
        let effective_repo = target_dir.unwrap_or(&self.repo_path);
        let repo_str = effective_repo.to_string_lossy().to_string();

        let mut metadata: HashMap<String, serde_json::Value> = HashMap::new();

        match task.role {
            AgentRole::Researcher => {
                let doc = format!(
                    "# Specification Document\n\n- Task: {}\n- Target: {}\n- Summary: Auto-generated spec by Agent-E.\n",
                    task.title, repo_str
                );
                metadata.insert("doc_content".into(), serde_json::Value::String(doc));
            }
            AgentRole::Developer => {
                let pkg_name = effective_repo
                    .file_name()
                    .and_then(|s| s.to_str())
                    .unwrap_or("my_app")
                    .replace('-', "_");

                let cargo_toml = format!(
                    "[package]\nname = \"{}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\n",
                    pkg_name
                );

                let main_rs = format!(
                    "//! Auto-generated by Multi-Agent Development Orchestrator (`mag`)\n\nfn main() {{\n    println!(\"Hello from mag multi-agent orchestrator!\");\n    let val = calculate_sum(10, 20);\n    println!(\"Sample calculation result: {{}}\", val);\n}}\n\npub fn calculate_sum(a: i32, b: i32) -> i32 {{\n    a + b\n}}\n\n#[cfg(test)]\nmod tests {{\n    use super::*;\n\n    #[test]\n    fn test_sum() {{\n        assert_eq!(calculate_sum(10, 20), 30);\n    }}\n}}\n"
                );

                metadata.insert(
                    "files".into(),
                    serde_json::json!({
                        "Cargo.toml": cargo_toml,
                        "src/main.rs": main_rs
                    }),
                );
                metadata.insert("command".into(), serde_json::Value::String("cargo check || true".into()));
            }
            AgentRole::Tester => {
                metadata.insert(
                    "test_command".into(),
                    serde_json::Value::String("cargo test || cargo check || python3 -m unittest discover || true".into()),
                );
            }
            _ => {}
        }

        let task_req = TaskRequest {
            task_id: task.id.clone(),
            r#type: task.role.to_string(),
            title: task.title.clone(),
            description: task.description.clone(),
            repository: repo_str,
            branch: format!("{}/{}", task.assigned_agent, task.id.to_lowercase()),
            timeout_seconds: 300,
            context_files: vec![],
            metadata,
        };

        let result = execute_task_for_agent(&agent, &task_req);
        let (verdict, next_status) = self.evaluator.evaluate(task, &result);

        task.status = next_status;
        task.result = Some(result.clone());
        if matches!(verdict, EvaluationVerdict::Retry { .. }) {
            task.retry_count += 1;
        }

        self.storage.save_task(task)?;
        Ok(result)
    }

    pub fn run_orchestration_loop(&self, target_dir: Option<&Path>, max_iterations: usize) -> Result<bool, OrchestratorError> {
        let mut iterations = 0;

        while iterations < max_iterations {
            iterations += 1;
            let all_tasks = self.storage.list_tasks()?;
            let ready_tasks = TaskScheduler::get_ready_tasks(&all_tasks);

            if ready_tasks.is_empty() {
                break;
            }

            for mut task in ready_tasks {
                println!("[*] Dispatching task [{}] '{}' to [{}]...", task.id, task.title, task.assigned_agent);
                let res = self.execute_task_locally(&mut task, target_dir)?;
                println!("    -> Result: {} | {}", res.status, res.summary);
            }
        }

        let final_tasks = self.storage.list_tasks()?;
        Ok(TaskScheduler::is_all_completed(&final_tasks))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_orchestrator_lifecycle() {
        let dir = tempdir().unwrap();
        let db_path = dir.path().join("test.sqlite");

        let orch = Orchestrator::new(dir.path(), &db_path).unwrap();
        let tasks = orch.decompose_requirement("Create hello library in Rust").unwrap();
        assert_eq!(tasks.len(), 5);

        let success = orch.run_orchestration_loop(Some(dir.path()), 10).unwrap();
        assert!(success);
        assert!(dir.path().join("Cargo.toml").exists());
        assert!(dir.path().join("src/main.rs").exists());
    }
}
