[package]
name = "mag-manager"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
mag-common.workspace = true
mag-config.workspace = true
mag-task.workspace = true
mag-agent.workspace = true
mag-logging.workspace = true
mag-storage.workspace = true
mag-git.workspace = true
mag-api.workspace = true
mag-container.workspace = true
mag-worker.workspace = true
mag-scheduler.workspace = true
chrono.workspace = true
libc.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tempfile.workspace = true
