//! Auto-generated by Multi-Agent Development Orchestrator (`mag`)

fn main() {
    println!("Hello from mag multi-agent orchestrator!");
    let val = calculate_sum(10, 20);
    println!("Sample calculation result: {}", val);
}

pub fn calculate_sum(a: i32, b: i32) -> i32 {
    a + b
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sum() {
        assert_eq!(calculate_sum(10, 20), 30);
    }
}
